from pathlib import Path

APP_NAME = "STT Local"
APPLICATION_SUPPORT_DIR = Path.home() / "Library" / "Application Support" / APP_NAME
CONFIG_PATH = APPLICATION_SUPPORT_DIR / "config.json"
PROCESSORS_DIR = APPLICATION_SUPPORT_DIR / "processors"
MODEL = "mlx-community/whisper-large-v3-turbo"
LANGUAGE = "en"
SAMPLE_RATE = 16_000
POLL_INTERVAL_SECONDS = 0.15
DEFAULT_IDLE_UNLOAD_SECONDS = 600.0
DEFAULT_DOUBLE_TAP_SECONDS = 0.20
DEFAULT_LONG_PRESS_SECONDS = 0.50
STREAM_STOP_TIMEOUT_SECONDS = 2.0
SPEECH_MODEL = "mlx-community/Kokoro-82M-bf16"
SPEECH_VOICE = "af_heart"
SPEECH_SAMPLE_RATE = 24_000
CONTROL_SOCKET = APPLICATION_SUPPORT_DIR / "control.sock"
VOICE_SESSIONS_DIR = APPLICATION_SUPPORT_DIR / "voice-sessions"
